/*
 * algo_If.h
 *
 *  Created on: 4 mar 2018
 *      Author: Zenc
 */

#ifndef SOURCE_ALGO_ALGO_IF_H_
#define SOURCE_ALGO_ALGO_IF_H_

#define SUDOKU_MAX_VALUE 9U

#define SUDOKU_ROW_COUNT 9U
#define SUDOKU_COLUMN_COUNT 9U
#define SUDOKU_SIZE (SUDOKU_ROW_COUNT * SUDOKU_COLUMN_COUNT)

#define SUDOKU_SQUARE_HEIGHT (SUDOKU_COLUMN_COUNT / SUDOKU_SQUARE_PER_COLUMN)
#define SUDOKU_SQUARE_PER_COLUMN 3U
#define SUDOKU_SQUARE_WIDTH (SUDOKU_ROW_COUNT / SUDOKU_SQUARE_PER_ROW)
#define SUDOKU_SQUARE_PER_ROW 3U
#define SUDOKU_SQUARE_SIZE (SUDOKU_SQUARE_HEIGHT *SUDOKU_SQUARE_PER_ROW)
#define SUDOKU_SQUARE_COUNT (SUDOKU_SQUARE_PER_COLUMN * SUDOKU_SQUARE_PER_ROW)

#endif /* SOURCE_ALGO_ALGO_IF_H_ */
